### ISSUE TITLE
undefined method `strategy_name' for #<AuthProvider::SimpleAuthProvider:0x0000000005cf4c48>

### ISSUE THREAD

**Issue by simonjamain** [sleede/fab-manager#113]
I'm trying to setup a development environment, I'm at the step where I launch the server with `foreman s -p 3000` and I am getting this : 

```
simonjamain:~/workspace/fab-manager (master) $ foreman s -p 3000
15:42:36 web.1    | started with pid 3457
15:42:36 worker.1 | started with pid 3458
15:42:36 mail.1   | started with pid 3459
15:42:41 mail.1   | Starting MailCatcher
15:42:41 mail.1   | ==> smtp://127.0.0.1:1025
15:42:42 mail.1   | ==> http://127.0.0.1:1080
15:42:51 worker.1 | W, [2018-06-27T15:42:51.216742 #3458]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
15:42:59 web.1    | W, [2018-06-27T15:42:51.035822 #3457]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
15:42:59 web.1    | => Booting Puma
15:42:59 web.1    | => Rails 4.2.10 application starting in development on http://0.0.0.0:3000
15:42:59 web.1    | => Run `rails server -h` for more startup options
15:42:59 web.1    | => Ctrl-C to shutdown server
15:42:59 web.1    | Puma starting in single mode...
15:42:59 web.1    | * Version 3.10.0 (ruby 2.3.6-p384), codename: Russell's Teapot
15:42:59 web.1    | * Min threads: 0, max threads: 16
15:42:59 web.1    | * Environment: development
15:42:59 web.1    | * Listening on tcp://0.0.0.0:3000
15:42:59 web.1    | Use Ctrl-C to stop
15:43:00 worker.1 | undefined method `strategy_name' for #<AuthProvider::SimpleAuthProvider:0x0000000005cf4c48>
15:43:00 worker.1 | /home/ubuntu/workspace/fab-manager/app/controllers/users/omniauth_callbacks_controller.rb:4:in `<class:OmniauthCallbacksController>'
15:43:00 worker.1 | /home/ubuntu/workspace/fab-manager/app/controllers/users/omniauth_callbacks_controller.rb:1:in `<top (required)>'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `load'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `block in load_file'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:647:in `new_constants_in'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:456:in `load_file'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:354:in `require_or_load'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:317:in `depend_on'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:233:in `require_dependency'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/engine.rb:471:in `each'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/engine.rb:471:in `block in eager_load!'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/engine.rb:469:in `each'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/engine.rb:469:in `eager_load!'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/engine.rb:346:in `eager_load!'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/application/finisher.rb:56:in `each'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:347:in `each'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:347:in `call'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
15:43:00 worker.1 | /usr/local/rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
15:43:00 worker.1 | /home/ubuntu/workspace/fab-manager/config/environment.rb:5:in `<top (required)>'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:241:in `boot_system'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:50:in `run'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/gems/sidekiq-3.3.4/bin/sidekiq:8:in `<top (required)>'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/bin/sidekiq:23:in `load'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/bin/sidekiq:23:in `<main>'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/bin/ruby_executable_hooks:15:in `eval'
15:43:00 worker.1 | /usr/local/rvm/gems/ruby-2.3.6@fab-manager/bin/ruby_executable_hooks:15:in `<main>'
15:43:00 worker.1 | exited with code 1
15:43:00 system   | sending SIGTERM to all processes
15:43:00 web.1    | - Gracefully stopping, waiting for requests to finish
15:43:00 web.1    | === puma shutdown: 2018-06-27 15:43:00 +0000 ===
15:43:00 web.1    | - Goodbye!
15:43:00 web.1    | Exiting
15:43:00 mail.1   | exited with code 0
15:43:00 web.1    | terminated by SIGTERM
```

Any ideas ?

ps : my distribution info

```
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by simonjamain** [comment]
I used the vagrant method and I paid more attention during the process this time...
It turned out that during `ADMIN_EMAIL='youradminemail' ADMIN_PASSWORD='youradminpassword' rake db:seed` my password was too short and this step failed, which I didn't notice at the time

**Comment by sylvainbx** [comment]
Sorry I missed to reply to your issue. Maybe be we can add a warning about the password length in the documentation. Thanks anyway for reporting your solution here.
