### ISSUE TITLE
Mise à jour 2.6.5

### ISSUE THREAD

**Issue by guidtz** [sleede/fab-manager#118]
Bonjour,

  j'ai suivi tout le changelog pour la mise à jour en 2.6.5. 
FabManager est en version Docker.

Problème après la mise à jour d'elasticsearch : 

`elasticsearch_1  | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
`
Ce qui fait que le conteneur elasticsearch est instable.

Merci pour votre aide.

**Comment by sylvainbx** [comment]
Bonjour @guidtz,

Est-ce que des erreurs ont été rapportés pendant la migration de version d'elasticsearch ?
Quel est le résultat de la commande ` curl "$ES_IP:9200/_cat/indices?v"` (en remplaçant `$ES_IP` par l'ip du container elasticsearch) ?

**Comment by guidtz** [comment]
J'ai pas vu d'erreur après la mise d'eslaticsearch. Par contre problème c'est que le conteneur est en restart constant donc impossible d'avoir une IP dessus :  

fabmanager_elasticsearch_1   /docker-entrypoint.sh elas ...   Restarting   

Je peux envoyer tout les logs ou tout les tests que vous voulez.

**Comment by sylvainbx** [comment]
En effet, c'est problématique !
Peux-tu rapporter ici le résultat de `docker logs -f fabmanager_elasticsearch_1` lorsque le container redémarre ?

**Comment by guidtz** [comment]
Voici les derniers logs : 

```
[2018-09-03T19:14:53,579][INFO ][o.e.n.Node               ] [] initializing ...
[2018-09-03T19:14:53,613][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/usr/share/elasticsearch/data], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
[2018-09-03T19:14:53,627][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.11.jar:5.6.11]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:261) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.11.jar:5.6.11]
	... 6 more
[2018-09-03T19:15:55,893][INFO ][o.e.n.Node               ] [] initializing ...
[2018-09-03T19:15:55,930][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/usr/share/elasticsearch/data], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
[2018-09-03T19:15:55,946][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.11.jar:5.6.11]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:261) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.11.jar:5.6.11]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.11.jar:5.6.11]
	... 6 more
```

**Comment by sylvainbx** [comment]
Bizarre, on dirait qu'une autre instance d'elasticsearch est déjà lancée ...

Tu peux vérifier le résultat des commandes suivantes :
```bash
docker ps -a
ps -ef | grep elastic
ls -l /apps/fabmanager/elasticsearch/elasticsearch/nodes # à modifier éventuellement selon ton installation
```

**Comment by guidtz** [comment]
Arg j'avais effectivement des process elastic qui tournaient mais plus de conteneurs donc j'ai pas eu l'idée d'aller voir ça.

Maintenant il ne redémarre toujours pas mais peut-être qu'il faut que je refasse la procédure de migration ?

**Comment by sylvainbx** [comment]
C'était des installations en local ou des containers ? Quelle est la version du container elastic de fab-manager ? Quelles étaient les versions des autres instances elasticsearch lancées ?

**Comment by guidtz** [comment]
Depuis le début on utilise la version conteneur. On avait une mise à jour en Mai ou Juin je crois par contre j'ai plus sous la main la version.

Voici les logs d'elasticsearch : 


```
elasticsearch_1  | [2018-09-03T19:11:47,004][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-09-03T19:11:47,034][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/usr/share/elasticsearch/data], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
elasticsearch_1  | [2018-09-03T19:11:47,046][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:261) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | [2018-09-03T19:12:49,108][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-09-03T19:12:49,134][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/usr/share/elasticsearch/data], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
elasticsearch_1  | [2018-09-03T19:12:49,144][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:261) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | [2018-09-03T19:13:51,289][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-09-03T19:13:51,330][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/usr/share/elasticsearch/data], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
elasticsearch_1  | [2018-09-03T19:13:51,344][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:261) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.11.jar:5.6.11]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | [2018-09-03T19:14:53,579][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-09-03T19:14:53,613][WARN ][o.e.d.e.NodeEnvironment  ] ES has detected the [path.data] folder using the cluster name as a folder [/usr/share/elasticsearch/data], Elasticsearch 6.0 will not allow the cluster name as a folder within the data path
```

Slts

**Comment by sylvainbx** [comment]
Peux-tu rapporter ici les résultats des [trois commandes listées plus haut](https://github.com/LaCasemate/fab-manager/issues/118#issuecomment-418267390) ?

**Comment by guidtz** [comment]
Excuse moi voici : 

# docker ps -a
```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                          PORTS                                      NAMES
e4bc117041a4        nginx:1.9            "nginx -g 'daemon of…"   33 hours ago        Up 32 hours                     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   fabmanager_nginx_1
a60b72620d1e        sleede/fab-manager   "/usr/bin/supervisord"   33 hours ago        Up 32 hours                     3000/tcp                                   fabmanager_fabmanager_1
8d7898c447b0        elasticsearch:5.6    "/docker-entrypoint.…"   33 hours ago        Restarting (1) 18 seconds ago                                              fabmanager_elasticsearch_1
dc17877a52cc        postgres:9.4         "docker-entrypoint.s…"   33 hours ago        Up 32 hours                     5432/tcp                                   fabmanager_postgres_1
4c0811e1da62        redis:3.0            "docker-entrypoint.s…"   8 days ago          Up 32 hours                     6379/tcp                                   fabmanager_redis_1
```

# ps -ef | grep elastic
```
root     28429 25140  0 15:24 pts/0    00:00:00 grep elastic
```

# ls -l elasticsearch/elasticsearch/nodes
```
total 12
drwxr-xr-x 4 systemd-network systemd-journal 4096 sept.  4 15:25 0
drwxr-xr-x 4 systemd-network systemd-journal 4096 août  24 22:03 1
drwxr-xr-x 4 systemd-network systemd-journal 4096 sept.  3 06:42 2
````

Slts

**Comment by sylvainbx** [comment]
Bizarre, l'utilisateur ayant les droits sur le dossier de données d'elastic ressemble à une installation sans docker-compose (docker classique). Dis moi quels sont les résultats de la séquence suivante ?
```bash
docker exec fabmanager_elasticsearch_1 touch /usr/share/elasticsearch/data/test
docker exec fabmanager_elasticsearch_1 ls -l /usr/share/elasticsearch/data
ls -l elasticsearch
```

**Comment by guidtz** [comment]
Je jure monsieur je l'ai fait avec le docker-compose dès le début :-) 

# docker exec fabmanager_elasticsearch_1 touch /usr/share/elasticsearch/data/test
Error response from daemon: Container 8d7898c447b0994162e48293d047dc02fac36e39ee9c5a7e2bad02487708a0f6 is restarting, wait until the container is running
# docker exec fabmanager_elasticsearch_1 ls -l /usr/share/elasticsearch/data
Error response from daemon: Container 8d7898c447b0994162e48293d047dc02fac36e39ee9c5a7e2bad02487708a0f6 is restarting, wait until the container is running
# ls -l elasticsearch
total 4
drwxr-xr-x 3 systemd-network systemd-journal 4096 mars  12 15:45 elasticsearch

**Comment by sylvainbx** [comment]
Essaye, en tant que root, de lancer :
```bash
chmod -R a+wx elasticsearch
```
Puis de réinitialiser le container :
```bash
docker rm -f fabmanager_elasticsearch_1
docker-compose down
docker-compose up -d
```

**Comment by guidtz** [comment]
C'est violent un a+wx :-) 

Toujours pareil : 
`elasticsearch_1  | Caused by: java.io.IOException: failed to read [id:15, legacy:false, file:/usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/stats/_state/state-15.st]
`
# ls -la elasticsearch/elasticsearch/nodes/0/indices/stats/_state/state-15.st 
-rwxrwxrwx 1 systemd-network systemd-journal 2082 mai   29 03:00 elasticsearch/elasticsearch/nodes/0/indices/stats/_state/state-15.st

**Comment by sylvainbx** [comment]
Bon au moins maintenant on sait que le problème ne vient pas de là ...
Tu dois avoir une autre instance d'elastic qui tourne ...
```bash
ps -ef | grep java
```

**Comment by guidtz** [comment]
Hélas ...

ps -ef |grep java
root      4521 25766  0 09:37 pts/0    00:00:00 grep java

Aucun autre process

**Comment by guidtz** [comment]
Si je vire le répertoire elasticsearch il va être récréé ? Et il y aurait pas une procédure pour réindexer les données ?

**Comment by guidtz** [comment]
ça te dis quoi ça : 
`elasticsearch_1  | Caused by: java.lang.IllegalStateException: unsupported compression: index was created before v2.0.0.beta1 and wasn't upgraded?`

**Comment by sylvainbx** [comment]
Ça, ça me parle ! Tu as vu ça où ? Ça veut dire que la migration n'a pas été effectuée ...

Pour relancer la migration, il te faut remettre elasticsearch 1.7 :
```bash
docker rm -f fabmanager_elasticsearch_1
docker-compose down
```
Puis modifier `docker-compose.yml` pour remettre à la ligne 29 :
```yml
  elasticsearch:
    image: elasticsearch:1.7
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    restart: always
```

Puis relancer les containers et la mise à niveau :
```bash
docker-compose up -d
\curl https://raw.githubusercontent.com/LaCasemate/fab-manager/master/scripts/elastic-upgrade.sh | bash
```
Copie/colle ici le journal de mise à niveau ...

**Comment by guidtz** [comment]
```
Waiting for ElasticSearch indices to have green status.

Installation of elasticsearch 5.6 was successful.
{"acknowledged":true,"shards_acknowledged":true,"index":"stats"}{
  "took" : 590,
  "timed_out" : false,
  "total" : 8,
  "updated" : 0,
  "created" : 8,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [ ]
}
Indices are reindexing. This may take a while, waiting to finish... 
Waiting for ElasticSearch indices to have green status

docs: 8, reindexed: 0
docs: 8, reindexed: 0
Reindex completed, deleting previous index...
{
  "acknowledged" : true
}
{
  "acknowledged" : true,
  "persistent" : { },
  "transient" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "all"
        }
      }
    }
  }
}
```
J'avais eu le méme résultat la dernière fois.

Faut que je lance ces commandes aussi ?
docker-compose run --rm fabmanager bundle exec rake fablab:fix:categories_slugs
docker-compose run --rm fabmanager bundle install
docker-compose run --rm fabmanager bundle exec rake db:seed

**Comment by sylvainbx** [comment]
Et le début du journal ? 

Pour les autres commandes, il faut les lancer mais si tu l'as déjà fait une fois, pas la peine de recommencer !

**Comment by guidtz** [comment]
Mince j'ai pas tout copié et depuis je me suis déco.

C'est normal ça : 
# docker-compose run --rm fabmanager bundle exec rake fablab:fix:categories_slugs
```
Starting fabmanager_redis_1 ... 
Starting fabmanager_redis_1 ... done
Starting fabmanager_postgres_1 ... done
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT 1  [["status", "active"]]
  AuthProvider Load (2.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT 1  [["status", "active"]]
  AuthProvider Load (0.2ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT 1  [["status", "active"]]
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT 1  [["status", "active"]]
  Category Load (0.5ms)  SELECT "categories".* FROM "categories"
sh: 1: wait_for_completion: not found
sh: 1: refresh: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   229  100   229    0     0    259      0 --:--:-- --:--:-- --:--:--   259
sh: 1: wait_for_completion: not found
sh: 1: refresh: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   228  100   228    0     0   2174      0 --:--:-- --:--:-- --:--:--  2192
sh: 1: sh: 1: refresh: not found
wait_for_completion: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   227  100   227    0     0   3661      0 --:--:-- --:--:-- --:--:--  3721
```

**Comment by sylvainbx** [comment]
Effectivement ce n'est pas normal. Du coup, je viens de publier le correctif sur [dev](https://github.com/LaCasemate/fab-manager/commits/dev).

**Comment by sylvainbx** [comment]
Néanmoins, j'aimerai bien comprendre pourquoi ta migration ne fonctionne pas. Si tu pouvais la relancer et me donner le journal complet ici, ça m'aiderait bien.

**Comment by guidtz** [comment]
Tu veux que je relance ça : 

curl https://raw.githubusercontent.com/LaCasemate/fab-manager/master/scripts/elastic-upgrade.sh | bash

**Comment by sylvainbx** [comment]
Pas seulement : toutes les étapes décrites [dans ce commentaire](https://github.com/LaCasemate/fab-manager/issues/118#issuecomment-418636620)

**Comment by sylvainbx** [comment]
Salut @guidtz,
Je viens de publier la [version 2.6.6](https://github.com/LaCasemate/fab-manager/releases/tag/v2.6.6) qui règle le problème avec `fablab:fix:categories_slugs`. Sinon je suis toujours preneur d'un log complet sur la mise à jour d'elastic.
Bonne journée

**Comment by guidtz** [comment]
Mince je suis désolé on est passé en prod j'avais pas envie d'y retoucher depuis.

**Comment by sylvainbx** [comment]
Tant que ça marche pour toi, c'est l'essentiel :)

**Comment by guidtz** [comment]
:-) on a fait la migration sur la version de décembre hier soir. J'ai pas encore entendu crier :-)
