### ISSUE TITLE
Galerie de projets

### ISSUE THREAD

**Issue by mipslab** [sleede/fab-manager#205]
Bonjour,
Un projet publié apparaît sur la page "Accueil" et dans "Mes projets" mais pas dans la galerie (avec ou sans connexion, pour aucun utilisateur).
Merci.

**Comment by sylvainbx** [comment]
La galerie est issue de la base de données elasticsearch, qui met parfois du temps à indexer les nouveaux éléments. Généralement cela se résout tout seul au bout de quelques minutes. Peux-tu confirmer que c'est bien le cas ?

**Comment by mipslab** [comment]
Non, toujours rien... Le projet apparaît dans Accueil et Mes projets mais pas dans la Galerie.

**Comment by sylvainbx** [comment]
Bizarre... Tu peux essayer de te connecter en tant qu'admin puis aller à https://url-de-ton-fab/admin/sidekiq/retries et regarder s'il y a des tentatives en échec avec ProjectIndexerWorker et rapporter ici le message d'erreur le cas échéant ?

**Comment by mipslab** [comment]
Je trouve ces deux erreurs :
- ActiveRecord::RecordNotFound: Couldn't find Project with 'id'=4
- NameError: uninitialized constant Faraday::Error::ConnectionFailed Did you mean? Faraday::ConnectionFailed

**Comment by sylvainbx** [comment]
Est-ce que tu peux me donner le retour de la commande suivante :
```
docker-compose exec fabmanager bundle | grep faraday
```

Je suis également preneur des fichiers suivants (via pastebin/dropbox/autre) : `/apps/fabmanager/log/worker-stdout.log` et `/apps/fabmanager/log/worker-stderr.log`

**Comment by Sebclem** [comment]
Salut !

C'est moi qui m'occupe de l'infra au mips !

faraday est en version 1.0.0:
```
Using faraday 1.0.0
```

Pour les logs, les dernieres lignes de stdout: https://pastebin.com/jpBXVxCC
et de stderr: https://pastebin.com/5CgB6dk7

**Comment by sylvainbx** [comment]
Ok, quel est le retour des commandes suivantes :

```
docker-compose exec fabmanager bundle exec rails runner "puts Project.all.map{|p| \"#{p.id}-#{p.state}\"}; STDOUT.flush"
```

```
docker-compose exec fabmanager bundle exec rails runner "puts Elasticsearch::Model.client.search(index: Project.index_name, type: Project.document_type)[\"hits\"][\"total\"]; STDOUT.flush"
```

**Comment by Sebclem** [comment]
Pour la premiere: 
```
6-published
3-draft
```
Par contre à la fin j'ai un message comme si une commande était execute avec les mauvais paramètre :

```
...
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]            # Skip namespace (affects only isolated applications)
  -r, [--ruby=PATH]                                        # Path to the Ruby binary of your choice
                                                           # Default: /usr/local/bin/ruby
....
```

Pour le deuxième j'ai une erreur: 
```
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

uninitialized constant Faraday::Error::ConnectionFailed
Did you mean?  Faraday::ConnectionFailed
```


De plus pour toutes les commandes j'ai ce message au debut, je sait pas si c'est normal:
```
Beginning in Rails 4, Rails ships with a `rails` binstub at ./bin/rails that
should be used instead of the Bundler-generated `rails` binstub.

If you are seeing this message, your binstub at ./bin/rails was generated by
Bundler instead of Rails.

You might need to regenerate your `rails` binstub locally and add it to source
control:

 rails app:update:bin           # Bear in mind this generates other binstubs
                                # too that you may or may not want (like yarn)

If you already have Rails binstubs in source control, you might be
inadverently overwriting them during deployment by using bundle install
with the --binstubs option.

If your application was created prior to Rails 4, here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rails app:update:bin          # Use the new Rails executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable
```

**Comment by sylvainbx** [comment]
OK, c'est très bizarre.
Je viens de publier la [version 4.4.2](https://github.com/sleede/fab-manager/releases/tag/v4.4.2), si tu peux mettre à jour et réessayer...

Tu peux aussi vérifier que elasticsearch est bien lancé (avec `docker-compose ps`) ?

**Comment by Sebclem** [comment]
Alors, j'ai des news, en revérifiant le docker compose, EL n'avais pas de réseau du coup fabmanager pouvez pas communiquer. 
Par contre j'ai une nouvelle erreur maintenant: 
```
  AuthProvider Load (0.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.6ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (1.1ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  DatabaseProvider Load (0.7ms)  SELECT  "database_providers".* FROM "database_providers" WHERE "database_providers"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Creating scope :published. Overwriting existing method Project.published.
  AuthProvider Load (0.7ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
2020-05-19 15:35:51 +0000: GET http://elasticsearch:9200/fablab/projects/_search [status:404, request:0.055s, query:N/A]
2020-05-19 15:35:51 +0000: < {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"fablab","index_uuid":"_na_","index":"fablab"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"fablab","index_uuid":"_na_","index":"fablab"},"status":404}
2020-05-19 15:35:51 +0000: [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"fablab","index_uuid":"_na_","index":"fablab"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"fablab","index_uuid":"_na_","index":"fablab"},"status":404}
Traceback (most recent call last):
        22: from bin/rails:4:in `<main>'
        21: from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        20: from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        19: from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
        18: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        17: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        16: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        15: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        14: from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        13: from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<main>'
        12: from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
        11: from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
        10: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         9: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         8: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         7: from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/runner/runner_command.rb:41:in `perform'
         6: from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/runner/runner_command.rb:41:in `eval'
         5: from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
         4: from /usr/local/bundle/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/search.rb:183:in `search'
         3: from /usr/local/bundle/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'
         2: from /usr/local/bundle/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
         1: from /usr/local/bundle/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"fablab","index_uuid":"_na_","index":"fablab"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"fablab","index_uuid":"_na_","index":"fablab"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
```

Je suis désoler mais j'y connais rien en EL

**Comment by sylvainbx** [comment]
Alors ça c'est une erreur très facile à résoudre  :) En effet, elle signifie simplement que la base de données elastic n'a pas été initialisée (elastic devrait être hors ligne à ce moment là). Du coup, pour ce faire :
```
docker-compose exec fabmanager bundle exec rails fablab:es:build_stats
```
Si ça ne fonctionne toujours pas, tu peux essayer de lancer cette commande en plus (mais essaye déjà en ayant lancé seulement la première commande, normalement cela devrait suffire) :
```
docker-compose exec fabmanager bundle exec rails fablab:es:build_projects_index
```

**Comment by Sebclem** [comment]
Nickel, tout est ok !

Merci beaucoup 👍 (je te laisse close l'issue, je peut pas le faire)

**Comment by sylvainbx** [comment]
Cool ! :)
Est-ce que tu as eu besoin de faire un `fablab:es:build_projects_index` ?

**Comment by Sebclem** [comment]
Nop, la première commande a suffi
