### ISSUE TITLE
(bug) Error on fetching machine availabilities (column slots.ex_start_at does not exist)

### ISSUE THREAD

**Issue by Guichaguri** [sleede/fab-manager#391]
**Describe the bug**
After running all migrations and fetching an availability (e.g. `/api/availabilities/machines/...`), the server returns with a 500 error.

I've noticed the [20220704084929_add_reservation_fields_to_slots_reservations](https://github.com/sleede/fab-manager/blob/master/db/migrate/20220704084929_add_reservation_fields_to_slots_reservations.rb) migration removes a few columns from the slots table, which are still being queried.

Unfortunately, I couldn't find exactly where it was pulling the `ex_start_at` column in the code.

**To Reproduce**
1. Click to reserve a machine
2. There are no slots in the calendar, and the `/api/availabilities/machines/...` returned an 500 error.
3. Open the log file

**Expected behavior**
The registered slots show up as expected and no error is thrown.

**Server (please complete the following information):**
 - Fab-manager version 5.4.13

**Browser (please complete the following information):**
 - Name: Chrome
- Version: 104.0.5112.101

**Additional context**

Error logs
```
Started GET "/api/availabilities/machines/impressora-3d-ultimaker-2-01-pla?start=2022-08-22T00%3A00%3A00&end=2022-08-29T00%3A00%3A00&timezone=America%2FSao_Paulo&_=1661178265944" for 200.211.62.61 at 2022-08-22 14:40:24 +0000
Processing by API::AvailabilitiesController#machine as JSON
  Parameters: {"start"=>"2022-08-22T00:00:00", "end"=>"2022-08-29T00:00:00", "timezone"=>"America/Sao_Paulo", "_"=>"1661178265944", "machine_id"=>"impressora-3d-ultimaker-2-01-pla"}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mSetting Load (0.3ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2[0m  [["name", "confirmation_required"], ["LIMIT", 1]]
  [1m[36mHistoryValue Load (0.2ms)[0m  [1m[34mSELECT  "history_values".* FROM "history_values" WHERE "history_values"."setting_id" = $1 ORDER BY "history_values"."created_at" DESC LIMIT $2[0m  [["setting_id", 51], ["LIMIT", 1]]
  [1m[36mRole Load (2.7ms)[0m  [1m[34mSELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))[0m  [["user_id", 2]]
  [1m[36mSetting Load (0.3ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2[0m  [["name", "visibility_yearly"], ["LIMIT", 1]]
  [1m[36mHistoryValue Load (0.3ms)[0m  [1m[34mSELECT  "history_values".* FROM "history_values" WHERE "history_values"."setting_id" = $1 ORDER BY "history_values"."created_at" DESC LIMIT $2[0m  [["setting_id", 30], ["LIMIT", 1]]
  [1m[36mSetting Load (0.3ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2[0m  [["name", "visibility_others"], ["LIMIT", 1]]
  [1m[36mHistoryValue Load (0.2ms)[0m  [1m[34mSELECT  "history_values".* FROM "history_values" WHERE "history_values"."setting_id" = $1 ORDER BY "history_values"."created_at" DESC LIMIT $2[0m  [["setting_id", 31], ["LIMIT", 1]]
  [1m[36mCACHE Role Load (0.0ms)[0m  [1m[34mSELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))[0m  [["user_id", 2]]
  [1m[36mMachine Load (0.5ms)[0m  [1m[34mSELECT  "machines".* FROM "machines" WHERE "machines"."slug" = $1 ORDER BY "machines"."id" ASC LIMIT $2[0m  [["slug", "impressora-3d-ultimaker-2-01-pla"], ["LIMIT", 1]]
  [1m[36mCACHE Role Load (0.0ms)[0m  [1m[34mSELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))[0m  [["user_id", 2]]
  [1m[35mSQL (1.7ms)[0m  [1m[34mSELECT "availabilities"."id" AS t0_r0, "availabilities"."start_at" AS t0_r1, "availabilities"."end_at" AS t0_r2, "availabilities"."available_type" AS t0_r3, "availabilities"."created_at" AS t0_r4, "availabilities"."updated_at" AS t0_r5, "availabilities"."nb_total_places" AS t0_r6, "availabilities"."destroying" AS t0_r7, "availabilities"."lock" AS t0_r8, "availabilities"."is_recurrent" AS t0_r9, "availabilities"."occurrence_id" AS t0_r10, "availabilities"."period" AS t0_r11, "availabilities"."nb_periods" AS t0_r12, "availabilities"."end_date" AS t0_r13, "availabilities"."slot_duration" AS t0_r14, "machines_availabilities"."id" AS t1_r0, "machines_availabilities"."machine_id" AS t1_r1, "machines_availabilities"."availability_id" AS t1_r2, "tags"."id" AS t2_r0, "tags"."name" AS t2_r1, "tags"."created_at" AS t2_r2, "tags"."updated_at" AS t2_r3, "plans"."id" AS t3_r0, "plans"."name" AS t3_r1, "plans"."amount" AS t3_r2, "plans"."interval" AS t3_r3, "plans"."group_id" AS t3_r4, "plans"."stp_plan_id" AS t3_r5, "plans"."created_at" AS t3_r6, "plans"."updated_at" AS t3_r7, "plans"."training_credit_nb" AS t3_r8, "plans"."is_rolling" AS t3_r9, "plans"."description" AS t3_r10, "plans"."type" AS t3_r11, "plans"."base_name" AS t3_r12, "plans"."ui_weight" AS t3_r13, "plans"."interval_count" AS t3_r14, "plans"."slug" AS t3_r15, "plans"."disabled" AS t3_r16, "plans"."monthly_payment" AS t3_r17, "plans"."plan_category_id" AS t3_r18, "slots"."id" AS t4_r0, "slots"."start_at" AS t4_r1, "slots"."end_at" AS t4_r2, "slots"."created_at" AS t4_r3, "slots"."updated_at" AS t4_r4, "slots"."availability_id" AS t4_r5, "slots"."ex_start_at" AS t4_r6, "slots"."ex_end_at" AS t4_r7, "slots"."canceled_at" AS t4_r8, "slots"."offered" AS t4_r9, "slots"."destroying" AS t4_r10 FROM "availabilities" INNER JOIN "slots" ON "slots"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "machines_availabilities" ON "machines_availabilities"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "availability_tags" ON "availability_tags"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "tags" ON "tags"."id" = "availability_tags"."tag_id" LEFT OUTER JOIN "plans_availabilities" ON "plans_availabilities"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "plans" ON "plans"."id" = "plans_availabilities"."plan_id" WHERE "machines_availabilities"."machine_id" = $1 AND (availabilities.start_at <= '2022-08-30 02:59:59.999999' AND availabilities.end_at >= '2022-08-22 03:00:00' AND available_type = 'machines') AND (slots.start_at > '2022-08-22 03:00:00' AND slots.end_at < '2022-08-30 02:59:59.999999') AND "availabilities"."lock" = $2[0m  [["machine_id", 7], ["lock", false]]
Completed 500 Internal Server Error in 21ms (ActiveRecord: 7.1ms | Elasticsearch: 0.0ms)
  
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column slots.ex_start_at does not exist
LINE 1: ...at" AS t4_r4, "slots"."availability_id" AS t4_r5, "slots"."e...
                                                             ^
HINT:  Perhaps you meant to reference the column "slots.start_at".
: SELECT "availabilities"."id" AS t0_r0, "availabilities"."start_at" AS t0_r1, "availabilities"."end_at" AS t0_r2, "availabilities"."available_type" AS t0_r3, "availabilities"."created_at" AS t0_r4, "availabilities"."updated_at" AS t0_r5, "availabilities"."nb_total_places" AS t0_r6, "availabilities"."destroying" AS t0_r7, "availabilities"."lock" AS t0_r8, "availabilities"."is_recurrent" AS t0_r9, "availabilities"."occurrence_id" AS t0_r10, "availabilities"."period" AS t0_r11, "availabilities"."nb_periods" AS t0_r12, "availabilities"."end_date" AS t0_r13, "availabilities"."slot_duration" AS t0_r14, "machines_availabilities"."id" AS t1_r0, "machines_availabilities"."machine_id" AS t1_r1, "machines_availabilities"."availability_id" AS t1_r2, "tags"."id" AS t2_r0, "tags"."name" AS t2_r1, "tags"."created_at" AS t2_r2, "tags"."updated_at" AS t2_r3, "plans"."id" AS t3_r0, "plans"."name" AS t3_r1, "plans"."amount" AS t3_r2, "plans"."interval" AS t3_r3, "plans"."group_id" AS t3_r4, "plans"."stp_plan_id" AS t3_r5, "plans"."created_at" AS t3_r6, "plans"."updated_at" AS t3_r7, "plans"."training_credit_nb" AS t3_r8, "plans"."is_rolling" AS t3_r9, "plans"."description" AS t3_r10, "plans"."type" AS t3_r11, "plans"."base_name" AS t3_r12, "plans"."ui_weight" AS t3_r13, "plans"."interval_count" AS t3_r14, "plans"."slug" AS t3_r15, "plans"."disabled" AS t3_r16, "plans"."monthly_payment" AS t3_r17, "plans"."plan_category_id" AS t3_r18, "slots"."id" AS t4_r0, "slots"."start_at" AS t4_r1, "slots"."end_at" AS t4_r2, "slots"."created_at" AS t4_r3, "slots"."updated_at" AS t4_r4, "slots"."availability_id" AS t4_r5, "slots"."ex_start_at" AS t4_r6, "slots"."ex_end_at" AS t4_r7, "slots"."canceled_at" AS t4_r8, "slots"."offered" AS t4_r9, "slots"."destroying" AS t4_r10 FROM "availabilities" INNER JOIN "slots" ON "slots"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "machines_availabilities" ON "machines_availabilities"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "availability_tags" ON "availability_tags"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "tags" ON "tags"."id" = "availability_tags"."tag_id" LEFT OUTER JOIN "plans_availabilities" ON "plans_availabilities"."availability_id" = "availabilities"."id" LEFT OUTER JOIN "plans" ON "plans"."id" = "plans_availabilities"."plan_id" WHERE "machines_availabilities"."machine_id" = $1 AND (availabilities.start_at <= '2022-08-30 02:59:59.999999' AND availabilities.end_at >= '2022-08-22 03:00:00' AND available_type = 'machines') AND (slots.start_at > '2022-08-22 03:00:00' AND slots.end_at < '2022-08-30 02:59:59.999999') AND "availabilities"."lock" = $2):
  
app/services/availabilities/availabilities_service.rb:23:in `map'
app/services/availabilities/availabilities_service.rb:23:in `machines'
app/controllers/api/availabilities_controller.rb:76:in `machine'
app/controllers/application_controller.rb:70:in `switch_locale'
```

**Comment by sylvainbx** [comment]
I was unable to reproduce this issue on various instances. 

Can you check that all the migrations were successfully passed? You can do it with the following command, which should outputs only `up` in the left column "Status":
```
curl -sSL run.fab.mn | bash -s -- "db:migrate:status"
```

**Comment by Guichaguri** [comment]
Here's the output:
```
ubuntu@ip-172-31-83-71:/apps/fabmanager$ curl -sSL run.fab.mn | bash -s -- "db:migrate:status"
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.5ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  OAuth2Provider Load (0.4ms)  SELECT  "o_auth2_providers".* FROM "o_auth2_providers" WHERE "o_auth2_providers"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  AuthProvider Load (3.7ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  OAuth2Provider Load (0.3ms)  SELECT  "o_auth2_providers".* FROM "o_auth2_providers" WHERE "o_auth2_providers"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  AuthProvider Load (0.3ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  OAuth2Provider Load (0.3ms)  SELECT  "o_auth2_providers".* FROM "o_auth2_providers" WHERE "o_auth2_providers"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  OAuth2Provider Load (0.3ms)  SELECT  "o_auth2_providers".* FROM "o_auth2_providers" WHERE "o_auth2_providers"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.4ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]
  AuthProvider Load (0.2ms)  SELECT  "auth_providers".* FROM "auth_providers" WHERE "auth_providers"."status" = $1 LIMIT $2  [["status", "active"], ["LIMIT", 1]]

database: fablab_production

 Status   Migration ID    Migration Name
--------------------------------------------------
   (0.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   up     20140409083104  Devise create users
   up     20140409083610  Rolify create roles
   up     20140409153915  Create profiles
   up     20140410101026  Create projects
   up     20140410140516  Create machines
   up     20140410162151  Create assets
   up     20140411152729  Create projects machines
   up     20140414141134  Add is allow contact to user
   up     20140415104151  Create project user
   up     20140415123625  Add author id to project
   up     20140416130838  Create project steps
   up     20140422085949  Create availabilities
   up     20140422090412  Create machines availabilities
   up     20140513152025  Add title to project step
   up     20140516083543  Create reservations
   up     20140516083909  Create slots
   up     20140516093335  Add reservable to reservation
   up     20140522115617  Create addresses
   up     20140522175539  Create components
   up     20140522175714  Create themes
   up     20140522180032  Create licences
   up     20140522180930  Create projects components
   up     20140522181011  Create projects themes
   up     20140522181148  Add tags to project
   up     20140523083230  Add licence id to project
   up     20140526144327  Add state to project
   up     20140527092045  Create notifications
   up     20140528134944  Add is valid to project user
   up     20140528140257  Add valid token to project user
   up     20140529145140  Create user trainings
   up     20140603084413  Create groups
   up     20140603085817  Create plans
   up     20140603164215  Create trainings pricings
   up     20140604094514  Add group to user
   up     20140604113611  Create trainings
   up     20140604113919  Create trainings machine
   up     20140604132045  Create trainings availabilities
   up     20140605125131  Add availability id to reservation
   up     20140605142133  Change machine id to training id from user training
   up     20140605151442  Change machine to training from trainings pricing
   up     20140609092700  Remove availability id form reservations
   up     20140609092827  Add availability to slot
   up     20140610153123  Add stp customer id to users
   up     20140610170446  Create subscriptions
   up     20140613150651  Add stp invoice id to reservation
   up     20140620131525  Add start at to subscription
   up     20140622121724  Create friendly id slugs
   up     20140622122944  Add slug to projects
   up     20140622145648  Add strip id to groups
   up     20140623023557  Add slug to machines
   up     20140624123359  Create credits
   up     20140624123814  Create users credits
   up     20140624124338  Add training credit nb to plan
   up     20140703100457  Change start at to expired at from subscription
   up     20140703231208  Add username to user
   up     20140703233420  Add index username to user
   up     20140703233942  Remove username from profiles
   up     20140703235739  Add slug to users
   up     20140710144142  Create events
   up     20140710144427  Create categories
   up     20140710144610  Create events categories
   up     20140711084809  Change event
   up     20140715095503  Add nb reserve places and nb reserve reduced places to reservation
   up     20140717143735  Add recurrence id to event
   up     20140722162046  Create invoices
   up     20140722162309  Create invoice items
   up     20140723075942  Add user id to invoice
   up     20140723171547  Remove description from invoice items
   up     20140723172610  Add invoiced to invoice items
   up     20140724125605  Remove invoiced from invoice items
   up     20140724131808  Add description to invoice items
   up     20140724132655  Add subscription id to invoice items
   up     20140728110430  Add reference to invoice
   up     20141002111736  Add canceled at to subscription
   up     20141110131407  Add to cancel to subscription
   up     20141215142044  Remove to cancel from subscription
   up     20141215153643  Create offer days
   up     20141217141648  Add nb total places to trainings
   up     20141217172843  Add nb total places to availability
   up     20150107103903  Add slug to trainings
   up     20150108082541  Add published at to projects
   up     20150112160349  Create statistic indices
   up     20150112160405  Create statistic types
   up     20150112160425  Create statistic sub types
   up     20150113112757  Add simple to statistic sub type
   up     20150114111132  Remove simple from statistic sub type
   up     20150114111243  Add simple to statistic type
   up     20150114141926  Create statistic fields
   up     20150114142032  Remove additional field from statistic index
   up     20150115143750  Add type to statistic field
   up     20150119082931  Rename statistic field type to data type
   up     20150119092557  Remove statistic type id from statistic sub type
   up     20150119093811  Create statistic type sub types
   up     20150119160758  Add table to statistic index
   up     20150119161004  Create statistic graphs
   up     20150127101521  Add ca to statistic index
   up     20150127155141  Add avoir mode to invoice
   up     20150127161235  Add avoir date to invoice
   up     20150127172510  Add invoice id to invoice
   up     20150128132219  Add subscription to expire to invoices
   up     20150218154032  Add receiver type and is send to notification
   up     20150428075148  Add is active attribute to users
   up     20150428091057  Create settings
   up     20150506090921  Add description to trainings
   up     20150507075506  Add ex start at to slots
   up     20150507075620  Add ex end at to slots
   up     20150512123546  Add attributes to plan
   up     20150520132030  Create prices
   up     20150526130729  Add base name to plans
   up     20150527153312  Add canceled at to slot
   up     20150529113555  Add default for training nb credit to plans
   up     20150601125944  Change stripe id to short name from groups
   up     20150603104502  Change short name to slug from group
   up     20150603104658  Add unique index to slug from group
   up     20150604081757  Add ui weight to plans
   up     20150604131525  Add meta data to notifications
   up     20150608142234  Add invoicing disabled to users
   up     20150609094336  Add interval count to plans
   up     20150615135539  Migrate plan stats
   up     20150617085623  Create custom assets
   up     20150701090642  Create stylesheets
   up     20150702150754  Create tags
   up     20150702151009  Create user tags
   up     20150706102547  Create availability tags
   up     20150707135343  Add offered to slots
   up     20150713090542  Change amount type in invoice items
   up     20150713151115  Add invoice item id to invoice item
   up     20150715135751  Add description to invoices
   up     20150915144448  Create auth providers
   up     20150915144939  Create o auth2 providers
   up     20150915152943  Create o auth2 mappings
   up     20150916091131  Change auth provider to polymorphic
   up     20150916093159  Create database providers
   up     20150921135557  Add sso id to user
   up     20150921135817  Add local model to o auth2 mapping
   up     20150922095921  Migrate endpoints to urls from o auth2 providers
   up     20150922100528  Remove resource url from o auth2 mappings
   up     20150924093917  Migrate url to endpoints from o auth2 providers
   up     20150924094138  Add resource endpoint to o auth2 mappings
   up     20150924094427  Rename resource endpoint from o auth2 mappings
   up     20150924141714  Add omniauth to users
   up     20151005133841  Add profile url to o auth2 providers
   up     20151008152219  Add auth token to users
   up     20151105125623  Create abuses
   up     20151210113548  Add merged at to users
   up     20160119131623  Add destroying to availability
   up     20160504085703  Create open API clients
   up     20160504085905  Create open API calls count tracings
   up     20160516090121  Add social fields to profile
   up     20160516124056  Add website to profile
   up     20160526095550  Add socials to profile
   up     20160526102307  Add job to profile
   up     20160602075531  Add step nb to project step
   up     20160613093842  Create unaccent function
   up     20160628092931  Rename courses workshops to events
   up     20160628124538  Create event themes
   up     20160628131408  Create events event themes
   up     20160628134211  Create age ranges
   up     20160628134303  Add age range id to event
   up     20160629091649  Rename range to name from age range
   up     20160630083438  Add slug to categories
   up     20160630083556  Add slug to age range
   up     20160630083759  Add slug to event theme
   up     20160630100137  Add event theme and age range to statistic field
   up     20160630140204  Add slugs to existing categories
   up     20160704095606  Create wallets
   up     20160704165139  Create wallet transactions
   up     20160714095018  Add public page to training
   up     20160718165434  Add wallet amount to invoice
   up     20160720124355  Add wallet transaction to invoice
   up     20160725131756  Add category id to event
   up     20160725131950  Singleize event categories
   up     20160725135112  Drop events categories
   up     20160726081931  Create exports
   up     20160726111509  Add user to export
   up     20160726131152  Rename type to stat type from export
   up     20160726144257  Add key to export
   up     20160728095026  Add is allow newsletter to users
   up     20160801145502  Create organizations
   up     20160801153454  Add profile to organization
   up     20160803085201  Create coupons
   up     20160803104701  Add coupon to invoice
   up     20160804073558  Remove usages from coupons
   up     20160808113850  Remove stp coupon id from coupons
   up     20160808113930  Add validity per user to coupon
   up     20160824080717  Create price categories
   up     20160824084111  Create event price categories
   up     20160825141326  Create tickets
   up     20160830154719  Migrate event reduced amount to price category
   up     20160831084443  Remove reduced amount from event
   up     20160831084519  Remove nb reserve reduced places from reservation
   up     20160905141858  Create statistic custom aggregations
   up     20160905142700  Add field to statistic custom aggregation
   up     20160906094739  Remove path from statistic custom aggregations
   up     20160906094847  Add es index es type to statistic custom aggregations
   up     20160915105234  Add transformation to o auth2 mapping
   up     20161123104604  Add amount off to coupons
   up     20170109085345  Add slug to plan
   up     20170213100744  Create spaces
   up     20170213101541  Create projects spaces
   up     20170213103438  Create spaces availabilities
   up     20170213142543  Add characteristics to space
   up     20170227104736  Create slots reservations
   up     20170227104934  Migrate slots reservations
   up     20170227113718  Remove reservation id from slots
   up     20170227114634  Add destroying to slot
   up     20170906100906  Add lock to availability
   up     20171004135605  Add disabled to plan
   up     20171005141522  Add disabled to group
   up     20171010143708  Add disabled to training
   up     20171011100640  Add disabled to machine
   up     20171011125217  Add disabled to space
   up     20181210105917  Rename expired at to expiration date from subscription
   up     20181217103256  Create history values
   up     20181217103441  Migrate settings value to history values
   up     20181217110454  Remove value from settings
   up     20190107103632  Create accounting periods
   up     20190107111749  Protect accounting periods
   up     20190110150532  Remove invoicing disabled from user
   up     20190211124135  Add footprint to invoice
   up     20190211124726  Add footprint to invoice item
   up     20190225101256  Add totals to accounting period
   up     20190225102847  Add footprint to accounting period
   up     20190227143153  Add environment to invoice
   up     20190314095931  Add operator to invoice
   up     20190320091148  Add footprint to history values
   up     20190521122429  Create invoicing profiles
   up     20190521123642  Create statistic profile
   up     20190521124609  Migrate profile to invoicing profile
   up     20190521151142  Migrate profile to statistic profile
   up     20190522115230  Migrate invoice to invoicing profile
   up     20190523123916  Migrate wallet to invoicing profile
   up     20190523140823  Migrate history value to invoicing profile
   up     20190528140012  Remove user id columns
   up     20190604064929  Migrate reservation to statistic profile
   up     20190604065348  Migrate subscription to statistic profile
   up     20190604070903  Migrate projet to statistic profile
   up     20190604075717  Remove statistic columns
   up     20190605141322  Create statistic profile trainings
   up     20190606074050  Migrate user trainings to statistic profile trainings
   up     20190606074801  Delete user trainings
   up     20190730085826  Add extension to export
   up     20190910131825  Add stp payment intent id to invoices
   up     20190910141336  Remove stp invoice id from reservations
   up     20190917123631  Rename avoir mode to payment method from invoices
   up     20190924140726  Create imports
   up     20191113103352  Add recurrence to availabilities
   up     20191127153729  Create i calendars
   up     20191202135507  Create i calendar events
   up     20200127111404  Add name to stylesheet
   up     20200206132857  Create plans availabilities
   up     20200218092221  Add tours to profile
   up     20200408101654  Match v1 models
   up     20200415141809  Add slot duration to availability
   up     20200511075933  Fix accounting periods
   up     20200622135401  Add pg search dmetaphone support functions
   up     20200623134900  Add search vector to project
   up     20200623141305  Update search vector of projects
   up     20200629123011  Update pg trgm
   up     20200721162939  Create footprint debugs
   up     20201027092149  Add monthly payment to plan
   up     20201027100746  Create payment schedules
   up     20201027101809  Create payment schedule items
   up     20201112092002  Add stp product id to objects
   up     20210416073410  Create payment gateway objects
   up     20210416083610  Migrate stripe ids to payment gateway objects
   up     20210521085710  Add object to invoice item
   up     20210525134018  Create payment schedule objects
   up     20210525150942  Remove transactable from wallet transaction
   up     20210608082748  Create plan categories
   up     20210621122103  Create prepaid packs
   up     20210621123954  Create statistic profile prepaid packs
   up     20211014135151  Add start at again to subscription
   up     20211018121822  Add start at to payment schedule
   up     20211220143400  Add duration to price
   up     20220111134253  Migrate payment schedule payment method check
   up     20220118123741  Fix subscription statistic types
   up     20220225143203  Drop table open API calls count tracings
   up     20220316133304  Allow update closed by on accounting periods
   up     20220322135836  Add scopes to o auth2 provider
   up     20220328141618  Create open id connect providers
   up     20220328144305  Rename o auth2 mappings to auth provider mappings
   up     20220328145017  Migrate o auth2 provider id from auth provider mappings
   up     20220422090245  Create proof of identity types
   up     20220422090709  Create proof of identity types groups
   up     20220425095244  Add mapped from sso to user
   up     20220426162334  Create proof of identity files
   up     20220428123828  Create proof of identity refusals
   up     20220428125751  Create join table proof of identity type proof of identity refusal
   up     20220429164234  Add validated at to user
   up     20220506143526  Create profile custom fields
   up     20220509105714  Create user profile custom fields
   up     20220517140916  Add description to plan category
   up     20220531160223  Change oidc scope to array
   up     20220704084929  Add reservation fields to slots reservations
   up     20220705125232  Insert missing slots
   up     20220720135828  Migrate slots notifications
```

**Comment by sylvainbx** [comment]
Very strange, it looks like your codebase is outdated but you're using an up-to-date database... Can you check that you didn't forced the app version in the docker-compose.yml? Or maybe you have some kind of cache somewhere?

**Comment by Guichaguri** [comment]
Looks like you were right, apparently rebooting the server fixed the problem.
It looks like it was running a partially older version, some endpoints were running queries on top of the new fields and some others were not, which doesn't make sense at all.

Anyway, it's working now. Thank you for the help :)
