### ISSUE TITLE
Statistics module not synchronizing

### ISSUE THREAD

**Issue by Guichaguri** [sleede/fab-manager#402]
**Describe the bug**
The statistics module is not synchronizing the Elastic Search database.

**To Reproduce**
1. Enable the statistics module in 5.4.19
2. Wait for the scheduled time
3. See that the Elastic Search database has not been updated and there are error logs in `worker-stdout.log`.

**Expected behavior**
The statistic data being properly updated every night.

**Server (please complete the following information):**
 - OS: `Ubuntu 20.04.4 LTS`
 - Kernel: `Linux ip-172-31-83-71 5.15.0-1020-aws #24~20.04.1-Ubuntu SMP Fri Sep 2 15:29:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - Fab-manager version: `5.4.19`

**Additional context**
StatisticWorker logs: (from `worker-stdout.log`)
```
2022-09-23T15:16:11.723Z pid=8 tid=ouge4mufs class=StatisticWorker jid=6ac7f013d200375a5cf133ec INFO: start
2022-09-23T15:16:11.723Z pid=8 tid=ougd41eco DEBUG: enqueued retry: {"retry":true,"queue":"default","class":"StatisticWorker","args":[],"jid":"6ac7f013d200375a5cf133ec","created_at":1663905600.1457186,"locale":"pt","enqueued_at":1663931498.828407,"error_message":"undefined local variable or method `default_options' for Statistics::BuilderService:Class","error_class":"NameError","failed_at":1663905600.1749961,"retry_count":11,"retried_at":1663931498.846946}
  [1m[36mSetting Load (0.4ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2[0m  [["name", "statistics_module"], ["LIMIT", 1]]
  [1m[36mHistoryValue Load (0.6ms)[0m  [1m[34mSELECT  "history_values".* FROM "history_values" WHERE "history_values"."setting_id" = $1 ORDER BY "history_values"."created_at" DESC LIMIT $2[0m  [["setting_id", 55], ["LIMIT", 1]]
2022-09-23T15:16:11.730Z pid=8 tid=ouge4mufs class=StatisticWorker jid=6ac7f013d200375a5cf133ec elapsed=0.008 INFO: fail
2022-09-23T15:16:11.730Z pid=8 tid=ouge4mufs WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"StatisticWorker","args":[],"jid":"6ac7f013d200375a5cf133ec","created_at":1663905600.1457186,"locale":"pt","enqueued_at":1663946171.7227573,"error_message":"undefined local variable or method `default_options' for Statistics::BuilderService:Class","error_class":"NameError","failed_at":1663905600.1749961,"retry_count":11,"retried_at":1663931498.846946},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"StatisticWorker\",\"args\":[],\"jid\":\"6ac7f013d200375a5cf133ec\",\"created_at\":1663905600.1457186,\"locale\":\"pt\",\"enqueued_at\":1663946171.7227573,\"error_message\":\"undefined local variable or method `default_options' for Statistics::BuilderService:Class\",\"error_class\":\"NameError\",\"failed_at\":1663905600.1749961,\"retry_count\":11,\"retried_at\":1663931498.846946}"}
2022-09-23T15:16:11.730Z pid=8 tid=ouge4mufs WARN: NameError: undefined local variable or method `default_options' for Statistics::BuilderService:Class
2022-09-23T15:16:11.730Z pid=8 tid=ouge4mufs WARN: /usr/src/app/app/services/statistics/builder_service.rb:6:in `generate_statistic'
/usr/src/app/app/workers/statistic_worker.rb:11:in `perform'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:196:in `execute_job'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/usr/local/bundle/gems/sidekiq-unique-jobs-7.1.23/lib/sidekiq_unique_jobs/middleware.rb:36:in `call'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/usr/local/bundle/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/middleware/i18n.rb:22:in `call'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:163:in `block in process'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:114:in `local'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:14:in `block in call'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:73:in `block in wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:72:in `wrap'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:257:in `stats'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:81:in `global'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:39:in `prepare'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:123:in `dispatch'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:162:in `process'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:78:in `process_one'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:68:in `run'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:56:in `watchdog'
/usr/local/bundle/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

**Comment by Guichaguri** [comment]
Looks like this was fixed in 5.4.21
