### ISSUE TITLE
Rebuilding assets fails in 5.7.0

### ISSUE THREAD

**Issue by albancrommer** [sleede/fab-manager#437]
# **Describe the bug**

After an upgrade to 5.7.0, the /public assets are not built.

# **To Reproduce**
1. Fresh new 5.6.5 instance
2. Upgrade docker to 5.7.0
3. Run the various `rake` tasks in CHANGELOG
4. Rm the assets as the doc recommands `rm -Rf public/packs/ public/assets/`
5. Try to compile new assets `docker compose run --rm fabmanager bundle exec rails assets:precompile`

It fails with stack dumps and no assets are produced.

# **Expected behavior**

The assets should compile

# **Logs**

```shell
root@fabmanager:/apps/fabmanager# docker-compose run fabmanager bundle exec rails assets:precompile
Starting fabmanager_postgres_1      ... done
Starting fabmanager_redis_1         ... done
Starting fabmanager_elasticsearch_1 ... done
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Shakapacker - Automatic installation of yarn packages is deprecated
Automatic installation of yarn packages when assets are precompiled is deprecated and will be removed in Shakapacker v7.
Please ensure you are installing yarn packages explicitly before the asset compilation.
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["object-to-formdata-tz@4.4.3"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-object-to-formdata-4.4.3-3059059d0f02ce90c7fdd9d83f491e8af34707ae-integrity/node_modules/object-to-formdata" as pattern ["object-to-formdata@npm:object-to-formdata-tz@4.4.3"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning "angular-bootstrap-switch > bootstrap-switch@3.4.0" has unmet peer dependency "bootstrap@^4.3.1".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.17".
info To upgrade, run the following command:
$ apk update && apk add -u yarn
Done in 229.88s.
I, [2023-02-20T13:38:23.393424 #1]  INFO -- : Compiling...
E, [2023-02-20T13:40:13.051797 #1] ERROR -- : 
COMPILATION FAILED:
EXIT STATUS: pid 235 exit 1
OUTPUTS:
assets by status 3.69 MiB [cached] 33 assets
Entrypoint application = js/runtime-27311a6acc134a1c4d45.js js/application-c620cd1f4814a0ec03af.js css/application-2ddd0bb4.css 28 auxiliary assets
Entrypoint plugins = js/runtime-27311a6acc134a1c4d45.js js/plugins-754a2ce6be840e8e6074.js 1 auxiliary asset
Entrypoint printer = js/runtime-27311a6acc134a1c4d45.js js/printer-3b88044eeb397d00d812.js css/printer-9c13df01.css 2 auxiliary assets
orphan modules 1.38 MiB (javascript) 3.11 MiB (asset) 2.05 KiB (runtime) [orphan] 48 modules
runtime modules 2.62 KiB 3 modules
cacheable modules 178 bytes (javascript) 590 KiB (css/mini-extract)
  javascript modules 178 bytes
    modules with errors 78 bytes [errors]
      ./app/frontend/application.js.erb 39 bytes [built] [code generated] [1 error]
      ./app/frontend/plugins.scss.erb 39 bytes [built] [code generated] [1 error]
    modules by path ./app/frontend/*.scss 100 bytes
      ./app/frontend/application.scss 50 bytes [built] [code generated]
      ./app/frontend/printer.scss 50 bytes [built] [code generated]
  css modules 590 KiB
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[10].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[10].use[1]!./app/frontend/application.scss 135 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[10].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[10].use[1]!./app/frontend/application.scss (1) 588 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[10].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[10].use[1]!./app/frontend/printer.scss 2.04 KiB [built] [code generated]

ERROR in ./app/frontend/application.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)

ERROR in ./app/frontend/plugins.scss.erb (./app/frontend/plugins.scss.erb.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[8].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[8].use[1]!./node_modules/rails-erb-loader/index.js!./node_modules/rails-erb-loader/index.js??ruleSet[1].rules[5].use[0]!./app/frontend/plugins.scss.erb)
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
 @ ./app/frontend/plugins.scss.erb

ERROR in ./app/frontend/plugins.scss.erb
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
    at tryRunOrWebpackError (/usr/src/app/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/usr/src/app/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/usr/src/app/node_modules/webpack/lib/Compilation.js:5008:18)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/usr/src/app/node_modules/neo-async/async.js:3485:9)
    at done (/usr/src/app/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:4986:43
    at symbolIterator (/usr/src/app/node_modules/neo-async/async.js:3482:9)
    at timesSync (/usr/src/app/node_modules/neo-async/async.js:2297:7)
-- inner error --
Error: Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
    at Object.<anonymous> (/usr/src/app/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!/usr/src/app/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[8].use[0]!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[8].use[1]!/usr/src/app/node_modules/rails-erb-loader/index.js!/usr/src/app/node_modules/rails-erb-loader/index.js??ruleSet[1].rules[5].use[0]!/usr/src/app/app/frontend/plugins.scss.erb:1:7)
    at /usr/src/app/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:5053:39
    at tryRunOrWebpackError (/usr/src/app/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/usr/src/app/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/usr/src/app/node_modules/webpack/lib/Compilation.js:5008:18)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/usr/src/app/node_modules/neo-async/async.js:3485:9)
    at done (/usr/src/app/node_modules/neo-async/async.js:3527:9)

Generated code for /usr/src/app/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!/usr/src/app/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[8].use[0]!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[8].use[1]!/usr/src/app/node_modules/rails-erb-loader/index.js!/usr/src/app/node_modules/rails-erb-loader/index.js??ruleSet[1].rules[5].use[0]!/usr/src/app/app/frontend/plugins.scss.erb
1 | throw new Error("Module build failed (from ./node_modules/rails-erb-loader/index.js):\nError: rails-erb-loader failed with code: 1\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/rails-erb-loader/index.js:128:16)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1100:16)\n    at Socket.<anonymous> (node:internal/child_process:458:11)\n    at Socket.emit (node:events:513:28)\n    at Pipe.<anonymous> (node:net:301:12)");

webpack 5.72.0 compiled with 3 errors in 97026 ms


/usr/src/app/lib/file_size_validator.rb:32:in `block in check_validity!': :maximum must be a nonnegative Integer (ArgumentError)
	from /usr/src/app/lib/file_size_validator.rb:29:in `each'
	from /usr/src/app/lib/file_size_validator.rb:29:in `check_validity!'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validator.rb:142:in `initialize'
	from /usr/src/app/lib/file_size_validator.rb:21:in `initialize'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:86:in `new'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:86:in `block in validates_with'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:85:in `each'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:85:in `validates_with'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/validates.rb:124:in `block in validates'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/validates.rb:114:in `each'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/validates.rb:114:in `validates'
	from /usr/src/app/app/models/supporting_document_file.rb:11:in `<class:SupportingDocumentFile>'
	from /usr/src/app/app/models/supporting_document_file.rb:5:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:356:in `require_or_load'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:334:in `depend_on'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:86:in `depend_on'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:246:in `require_dependency'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:477:in `each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:477:in `block in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:475:in `each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:475:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:356:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:69:in `each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
	from /usr/src/app/config/environment.rb:5:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require_environment!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/actions.rb:28:in `require_environment!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/runner/runner_command.rb:29:in `perform'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from bin/rails:4:in `<main>'
/usr/src/app/lib/file_size_validator.rb:32:in `block in check_validity!': :maximum must be a nonnegative Integer (ArgumentError)
	from /usr/src/app/lib/file_size_validator.rb:29:in `each'
	from /usr/src/app/lib/file_size_validator.rb:29:in `check_validity!'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validator.rb:142:in `initialize'
	from /usr/src/app/lib/file_size_validator.rb:21:in `initialize'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:86:in `new'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:86:in `block in validates_with'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:85:in `each'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/with.rb:85:in `validates_with'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/validates.rb:124:in `block in validates'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/validates.rb:114:in `each'
	from /usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/validations/validates.rb:114:in `validates'
	from /usr/src/app/app/models/supporting_document_file.rb:11:in `<class:SupportingDocumentFile>'
	from /usr/src/app/app/models/supporting_document_file.rb:5:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:356:in `require_or_load'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:334:in `depend_on'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:86:in `depend_on'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:246:in `require_dependency'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:477:in `each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:477:in `block in eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:475:in `each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:475:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:356:in `eager_load!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:69:in `each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
	from /usr/src/app/config/environment.rb:5:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require_environment!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/actions.rb:28:in `require_environment!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/runner/runner_command.rb:29:in `perform'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from bin/rails:4:in `<main>'
```

# **Server (please complete the following information):**
 - OS: Debian 11
 - Kernel: Linux fabmanager 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
 - Fab-manager version : [release-v5.7.0](https://hub.docker.com/layers/sleede/fab-manager/release-v5.7.0/images/sha256-fe5fa30ed8f43a3e6e09e1de6f1ca1ac7ddbfcef3a27350330b92074c40423d2?context=explore)

# **Browser (please complete the following information):**
 - Name: Chromium Linux
 - Version: Version 107.0.5304.87

**Comment by sylvainbx** [comment]
Corrigé dans [v5.7.1](https://github.com/sleede/fab-manager/releases/tag/v5.7.1)
