### ISSUE TITLE
5.7.1 Angular crash

### ISSUE THREAD

**Issue by albancrommer** [sleede/fab-manager#438]
# **Describe the bug**

The app shows a blank page and the browser console shows numerous errors.

# **To Reproduce**
1. Update to 5.7.1
2. Go to home page

# **Expected behavior**

The app should work.

# Logs

```javascript
Uncaught SyntaxError: Unexpected token '&' (at (index):54:46)
moment.js:287 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
M @ moment.js:287
E @ moment.js:339
bn @ moment.js:2147
(anonymous) @ fr.js:1
(anonymous) @ fr.js:1
136 @ fr.js:1
a @ fr.js:1
135 @ fr.js:1
a @ fr.js:1
0 @ fr.js:1
(anonymous) @ fr.js:1
90920 @ fr.js:1
u @ bootstrap:19
89465 @ application-778912fc887fac7725e9.js:1
u @ bootstrap:19
t @ application-778912fc887fac7725e9.js:1
(anonymous) @ application-778912fc887fac7725e9.js:1
u.O @ chunk loaded:25
(anonymous) @ application-778912fc887fac7725e9.js:1
t @ jsonp chunk loading:36
(anonymous) @ application-778912fc887fac7725e9.js:1
app.js:143 Uncaught ReferenceError: Fablab is not defined
    at 31511 (app.js:143:15)
    at u (bootstrap:19:32)
    at 89465 (application.js.erb:82:1)
    at u (bootstrap:19:32)
    at t (application-778912fc887fac7725e9.js:1:1557996)
    at application-778912fc887fac7725e9.js:1:1558037
    at u.O (chunk loaded:25:12)
    at application-778912fc887fac7725e9.js:1:1558060
    at t (jsonp chunk loading:36:28)
    at application-778912fc887fac7725e9.js:1:65
31511 @ app.js:143
u @ bootstrap:19
89465 @ application.js.erb:82
u @ bootstrap:19
t @ application-778912fc887fac7725e9.js:1
(anonymous) @ application-778912fc887fac7725e9.js:1
u.O @ chunk loaded:25
(anonymous) @ application-778912fc887fac7725e9.js:1
t @ jsonp chunk loading:36
(anonymous) @ application-778912fc887fac7725e9.js:1
angular.js:138 Uncaught Error: [$injector:modulerr] Failed to instantiate module application due to:
Error: [$injector:modulerr] Failed to instantiate module application.router due to:
Error: [$injector:nomod] Module 'application.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.


https://errors.angularjs.org/1.8.2/$injector/modulerr?p0=application&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20application.router%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'application.router'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0A%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.8.2%2F%24injector%2Fmodulerr%3Fp0%3Dapplication.router%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'application.router'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttps%253A%252F%252Ferrors.angularjs.org%252F1.8.2%252F%2524injector%252Fnomod%253Fp0%253Dapplication.router%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5039680%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5219676%250A%2520%2520%2520%2520at%2520r%2520(https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5219361)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5219646%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5064054%250A%2520%2520%2520%2520at%2520j%2520(https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5040387)%250A%2520%2520%2520%2520at%2520v%2520(https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5063999)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5064085%250A%2520%2520%2520%2520at%2520j%2520(https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5040387)%250A%2520%2520%2520%2520at%2520v%2520(https%253A%252F%252Ffabmanager.crommer.net%252Fpacks%252Fjs%252F435-40e3458c0de9c9035da4.js%253A2%253A5063999)%0A%20%20%20%20at%20https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5039680%0A%20%20%20%20at%20https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5064324%0A%20%20%20%20at%20j%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5040387)%0A%20%20%20%20at%20v%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5063999)%0A%20%20%20%20at%20https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5064085%0A%20%20%20%20at%20j%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5040387)%0A%20%20%20%20at%20v%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5063999)%0A%20%20%20%20at%20Qa%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5063328)%0A%20%20%20%20at%20t%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5049238)%0A%20%20%20%20at%20Ae%20(https%3A%2F%2Ffabmanager.crommer.net%2Fpacks%2Fjs%2F435-40e3458c0de9c9035da4.js%3A2%3A5049553)
    at angular.js:138:12
    at angular.js:5127:15
    at j (angular.js:388:20)
    at v (angular.js:5087:5)
    at Qa (angular.js:5004:19)
    at t (angular.js:1963:20)
    at Ae (angular.js:1984:12)
    at Ee (angular.js:1869:5)
    at HTMLDocument.<anonymous> (angular.js:36595:5)
    at c (jquery.js:3766:29)
    
```

# **Server (please complete the following information):**
 - OS: Debian 11
 - Kernel: Linux fabmanager 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
 - Fab-manager version : release-v5.7.1
 
# **Browser (please complete the following information):**
 - Name: Chromium Linux
 - Version: Version 107.0.5304.87

**Comment by sylvainbx** [comment]
Looks like you have an issue with your assets. Can you try in the following order:
- `cd /apps/fabmanager/`
- `sudo rm -rf public/packs`
- `mkdir public/packs`
- `chmod a+rw public/packs`
- `curl -sSL run.fab.mn | bash -s -- 'assets:precompile'`
- `docker-compose down && docker-compose up -d`

**Comment by albancrommer** [comment]
I actually ran the rake recompile task yesterday after moving to 5.71, but I'll follow your instructions.

**Comment by albancrommer** [comment]
[Solved]

I tried your recommanded actions, but it seemed to fail at rebuilding the assets as the app was still failing to load.

Yet after rereading the `rake` logs, it was only only warnings and nothing critical.

I double checked the web inspector console when loading the home. 

The error was coming from the following line:

```
      Fablab.maxSupportingDocumentFileSize = &#39;5242880&#39;;
```
The config file had the default :
```
# 5242880 = 5 megabytes
MAX_SUPPORTING_DOCUMENT_FILE_SIZE='5242880'
```

I removed the single quotes around the value. And it works.

So... weird that the quotes for __this__ value are html encoded ?

And maybe that would explain the #436 bug.

**Comment by sylvainbx** [comment]
Thanks for the feedback @albancrommer. Those quotes should not be necessary anymore with the new versions, I'll remove them from the default env file. Have you made a new try about #436 ?

**Comment by albancrommer** [comment]
@sylvainbx Yes, got new informations about that bug. Check it out and tell me what you think.
