### ISSUE TITLE
Error installing ffi gem as a part of fab-manager installation

### ISSUE THREAD

**Issue by abhas** [sleede/fab-manager#460]
**Describe the bug**

While starting the fab-manager container, I think it installed the required gems as a part of the start process. During that, the container stops citing the following error:

``` 
FI::NotFoundError: Function 'statvfs64' not found in [libc.so]
/usr/local/bundle/gems/ffi-1.15.5/lib/ffi/library.rb:273:in `attach_function'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/unix/sys/filesystem/functions.rb:24:in `<module:Functions>'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/unix/sys/filesystem/functions.rb:5:in `<class:Filesystem>'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/unix/sys/filesystem/functions.rb:4:in `<module:Sys>'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/unix/sys/filesystem/functions.rb:3:in `<main>'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/unix/sys/filesystem.rb:3:in `require_relative'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/unix/sys/filesystem.rb:3:in `<main>'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/filesystem.rb:13:in `require_relative'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys/filesystem.rb:13:in `<main>'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys-filesystem.rb:1:in `require_relative'
/usr/local/bundle/gems/sys-filesystem-1.4.3/lib/sys-filesystem.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/runtime.rb:55:in `each'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/runtime.rb:55:in `block in require'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/runtime.rb:44:in `each'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/runtime.rb:44:in `require'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler.rb:195:in `require'
/usr/src/app/config/application.rb:20:in `<top (required)>'
/usr/src/app/Rakefile:6:in `require_relative'
/usr/src/app/Rakefile:6:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
``` 

**To Reproduce**

Install fab-manager using the automated install script.

**Comment by gnepud** [comment]
Hi @abhas 

This problem is fixed. You can retry with le script of installation.

Thanks
