### ISSUE TITLE
db:migrate failure on "insert_custom_aggregations"

### ISSUE THREAD

**Issue by lejallec** [sleede/fab-manager#55]
Hi,

   I am trying to install Fab Manager on a local computer.
   It all works fine until the "db:migrate" command ; it fails there. I have retried several times and it fails at the same place and with the same error message on each tentative.

Here is the command :

```bash
bundle exec rake db:migrate
```

Here is the error message :
```bash
== 20160906145713 InsertCustomAggregations: migrating =========================
  StatisticIndex Load (0.4ms)  SELECT  "statistic_indices".* FROM "statistic_indices" WHERE "statistic_indices"."es_type_key" = $1 LIMIT 1  [["es_type_key", "machine"]]
   (0.4ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `id' for nil:NilClass
/usr/src/app/db/migrate/20160906145713_insert_custom_aggregations.rb:5:in `up'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
NoMethodError: undefined method `id' for nil:NilClass
/usr/src/app/db/migrate/20160906145713_insert_custom_aggregations.rb:5:in `up'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Can you please help me fixing this so that I can finalize my installation ?
Thank you :-)

**Comment by sylvainbx** [comment]
Hi,
This is a bug (and this is my fault), thanks for reporting.
I will commit a patch as soon as possible and this will be fixed in the next stable release.

Meanwhile, if you want to fix it, to finalize your installation, you'll have to delete `db/migrate/20160906145713_insert_custom_aggregations.rb` and add [these lines of code](https://gist.github.com/sylvainbx/13c94674009316571d011adb0cef62dd) at the end of the file `db/seeds.rb`.

Then you should be able to run your command again:

```bash
bundle exec rake db:migrate
```

**Comment by lejallec** [comment]
Hi,

   I'll check your patch.
   Big thanks for your fast answer and the big work on this application ! :-)

**Comment by sylvainbx** [comment]
New stable [version 2.4.7](https://github.com/LaCasemate/fab-manager/releases/tag/v2.4.7), released just now fixes the issue.

**Comment by lejallec** [comment]
Big thanks again.
I confirm everything is now fine. Using docker, it took around 10 minutes to have everything up and running from scratch :-)
Great job !
